# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  uptimerobot_api_key: "{{ env.UPTIMEROBOT_API_KEY }}"
}

# override variables
variables:
  trmnl: {
    plugin_settings: {
      instance_name: UptimeRobot
    }
  }
  # monitors:
  # - friendly_name: Example Website 0
  #   url: https://paused.example.com
  #   status: 0
  # - friendly_name: Example Website 1
  #   url: https://not-checked-yet.example.com
  #   status: 1
  # - friendly_name: Example Website 2
  #   url: https://up.example.com
  #   status: 2
  # - friendly_name: Example Website 8
  #   url: https://seems-down.example.com
  #   status: 8
  # - friendly_name: Example Website 9
  #   url: https://down.example.com
  #   status: 9
  # - friendly_name: Example Website 2
  #   url: https://up.example.com
  #   status: 2
  # - friendly_name: Example Website 2
  #   url: https://up.example.com
  #   status: 2
  # - friendly_name: Example Website 2
  #   url: https://up.example.com
  #   status: 2
  # - friendly_name: Example Website 2
  #   url: https://up.example.com
  #   status: 2
  # - friendly_name: Example Website 2
  #   url: https://up.example.com
  #   status: 2
